use embassy_nrf::{peripherals, Peri};

pub struct Board {
    pub led: Peri<'static, peripherals::P0_15>,
    pub button: Peri<'static, peripherals::P1_00>,
    pub gps_uart_rx: Peri<'static, peripherals::P0_22>,
    pub gps_uart_tx: Peri<'static, peripherals::P0_20>,
    pub gps_en: Peri<'static, peripherals::P0_24>,
    pub i2c_sda: Peri<'static, peripherals::P1_04>,
    pub i2c_scl: Peri<'static, peripherals::P0_11>,
    pub spi_miso: Peri<'static, peripherals::P0_02>,
    pub spi_mosi: Peri<'static, peripherals::P1_15>,
    pub spi_sck: Peri<'static, peripherals::P1_11>,
    pub spi_cs: Peri<'static, peripherals::P1_13>,
    pub battery_adc: Peri<'static, peripherals::P0_31>,
    pub v3v3_en: Peri<'static, peripherals::P0_13>,
    pub serial2_rx: Peri<'static, peripherals::P0_06>,
    pub serial2_tx: Peri<'static, peripherals::P0_08>,
    pub uarte0: Peri<'static, peripherals::UARTE0>,
    pub twispi0: Peri<'static, peripherals::TWISPI0>,
    pub spi3: Peri<'static, peripherals::SPI3>,
    pub usbd: Peri<'static, peripherals::USBD>,
    pub saadc: Peri<'static, peripherals::SAADC>,
    pub timer1: Peri<'static, peripherals::TIMER1>,
    pub ppi_ch8: Peri<'static, peripherals::PPI_CH8>,
    pub ppi_ch9: Peri<'static, peripherals::PPI_CH9>,
    pub ppi_group1: Peri<'static, peripherals::PPI_GROUP1>,
    // MPSL peripherals
    pub rtc0: Peri<'static, peripherals::RTC0>,
    pub timer0: Peri<'static, peripherals::TIMER0>,
    pub temp: Peri<'static, peripherals::TEMP>,
    pub ppi_ch19: Peri<'static, peripherals::PPI_CH19>,
    pub ppi_ch30: Peri<'static, peripherals::PPI_CH30>,
    pub ppi_ch31: Peri<'static, peripherals::PPI_CH31>,
    // SDC peripherals
    pub rng: Peri<'static, peripherals::RNG>,
    pub ppi_ch17: Peri<'static, peripherals::PPI_CH17>,
    pub ppi_ch18: Peri<'static, peripherals::PPI_CH18>,
    pub ppi_ch20: Peri<'static, peripherals::PPI_CH20>,
    pub ppi_ch21: Peri<'static, peripherals::PPI_CH21>,
    pub ppi_ch22: Peri<'static, peripherals::PPI_CH22>,
    pub ppi_ch23: Peri<'static, peripherals::PPI_CH23>,
    pub ppi_ch24: Peri<'static, peripherals::PPI_CH24>,
    pub ppi_ch25: Peri<'static, peripherals::PPI_CH25>,
    pub ppi_ch26: Peri<'static, peripherals::PPI_CH26>,
    pub ppi_ch27: Peri<'static, peripherals::PPI_CH27>,
    pub ppi_ch28: Peri<'static, peripherals::PPI_CH28>,
    pub ppi_ch29: Peri<'static, peripherals::PPI_CH29>,
}

impl Board {
    pub fn new(p: embassy_nrf::Peripherals) -> Self {
        Self {
            led: p.P0_15,
            button: p.P1_00,
            gps_uart_rx: p.P0_22,
            gps_uart_tx: p.P0_20,
            gps_en: p.P0_24,
            i2c_sda: p.P1_04,
            i2c_scl: p.P0_11,
            spi_miso: p.P0_02,
            spi_mosi: p.P1_15,
            spi_sck: p.P1_11,
            spi_cs: p.P1_13,
            battery_adc: p.P0_31,
            v3v3_en: p.P0_13,
            serial2_rx: p.P0_06,
            serial2_tx: p.P0_08,
            uarte0: p.UARTE0,
            twispi0: p.TWISPI0,
            spi3: p.SPI3,
            usbd: p.USBD,
            saadc: p.SAADC,
            timer1: p.TIMER1,
            ppi_ch8: p.PPI_CH8,
            ppi_ch9: p.PPI_CH9,
            ppi_group1: p.PPI_GROUP1,
            // MPSL
            rtc0: p.RTC0,
            timer0: p.TIMER0,
            temp: p.TEMP,
            ppi_ch19: p.PPI_CH19,
            ppi_ch30: p.PPI_CH30,
            ppi_ch31: p.PPI_CH31,
            // SDC
            rng: p.RNG,
            ppi_ch17: p.PPI_CH17,
            ppi_ch18: p.PPI_CH18,
            ppi_ch20: p.PPI_CH20,
            ppi_ch21: p.PPI_CH21,
            ppi_ch22: p.PPI_CH22,
            ppi_ch23: p.PPI_CH23,
            ppi_ch24: p.PPI_CH24,
            ppi_ch25: p.PPI_CH25,
            ppi_ch26: p.PPI_CH26,
            ppi_ch27: p.PPI_CH27,
            ppi_ch28: p.PPI_CH28,
            ppi_ch29: p.PPI_CH29,
        }
    }
}
